// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zibeoajegcgvyqsuqxnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYmVvYWplZ2Nndnlxc3VxeG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTI3NzgsImV4cCI6MjA3MTQ4ODc3OH0.pkEmWq_q22a3D0vPu5x5X-8UxZ8ExPC9P24E7JbSaF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});